#!/usr/bin/php-cli
<?php

$db_php_version = "0.7";

// API Information
$api_url = "https://mohawk.alma.edu/arduino/";

$filename = "/var/www/html/device_code.php";
$queue_name = "/var/www/html/queue";
if (!file_exists($filename)) {
	$contents = "<?php\n//DO NOT EDIT THIS FILE\n\$device_code = \"".uniqid("",true)."\";\n";
	file_put_contents($filename, $contents);
}

include $filename;

// Variables
$temperature = $argv[1]; 
$humidity = $argv[2];
$sensor1Value = $argv[3];
$sensor2Value = $argv[4];
$sensor3Value = $argv[5];
$sensor4Value = $argv[6];
$sensor5Value = $argv[7];



if (!function_exists('curl_init')) {
	trigger_error('CURL is not available to PHP', E_USER_ERROR);
	exit;
}

//extract data from the post
extract($_POST);

//set data variables
$data = array(
	'temperature' => $temperature,
	'humidity' => $humidity,
	'sensor1Value' => $sensor1Value,
	'sensor2Value' => $sensor2Value,
	'sensor3Value' => $sensor3Value,
	'sensor4Value' => $sensor4Value,
	'sensor5Value' => $sensor5Value, 
	'tstamp' => time()
	);


file_put_contents($queue_name,serialize($data)."\n##\n",FILE_APPEND);

$post = array(
	'device_code' => $device_code,
	'db_php_version' => $db_php_version,
	"tstamp" => time(), 
	"queue" => file_get_contents($queue_name)
	);

$result = "NOT RUN";

/* */
//open connection
$ch = curl_init();

//set the url, number of POST vars, POST data
curl_setopt($ch,CURLOPT_URL, $api_url);
curl_setopt($ch,CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10); 
curl_setopt($ch, CURLOPT_FRESH_CONNECT, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 20); //timeout in seconds

//execute post
$result = curl_exec($ch);

//close connection
curl_close($ch);
/* */

if ($result == "UPDATE" || $result == "GOOD") {
	echo "Data received\n";	
	//rename($queue_name, $queue_name.".".date('Y-m-d-H-i-s'));
	unlink($queue_name);
	//echo $result."\n\n";
	
	if ($result == "UPDATE") {
		//open connection
		$ch = curl_init();

		//set the url, number of POST vars, POST data
		curl_setopt($ch,CURLOPT_URL, $api_url."?update_db_php");
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10); 
		curl_setopt($ch, CURLOPT_FRESH_CONNECT, 1);
		curl_setopt($ch, CURLOPT_TIMEOUT, 20); //timeout in seconds

		//execute post
		$result = curl_exec($ch);

		//close connection
		curl_close($ch);
		
		if (substr($result,0,14) == "#!/usr/bin/php") {
			if (file_put_contents("/var/www/html/db.php", $result))
				echo "updated\n";
			else
				echo "update failed\n";
		} else {
			echo "update failed 2\n";
			echo $result."\n";
		}
	}
} else {
	echo "queued\n";
  trigger_error("Error submitting data\n".$result."\n", E_USER_ERROR);
}

